[boxer.crypto]
cryptomode=1 # 0 - AES256-GCM , 1 - AES256-CBC

[[boxer.crypto.keys]]
id="key1"
value="a15bc78675b379b8ca76927ad15e6c10f313931213ab70d49afa97233e05cd80"
entity="entity1"
default=true

[[boxer.crypto.keys]]
id="key1"
value="5d4440746f4460d94ffe0d41517c886b55143ebe2eca72673c30ae02bfe7d4cc"
entity="entity2"
default=true

[boxer.keycache]
ttl="30m"
cleanupinterval="10m"

[multichain]
chainname="chain1"
username="username"
password="password"
nativeentity="entity1"
