// Code generated by go generate; DO NOT EDIT.
// This file was generated by gen.go at
// 2018-05-10 16:20:54.423246321 +0530 IST m=+0.001819662
package agent

// RegisterGeneratedAPI ...
func(s *Service) RegisterGeneratedAPI() {
	s.h.RegisterAPI("getstreamitem",s.Getstreamitem)
	s.h.RegisterAPI("liststreamkeyitems",s.Liststreamkeyitems)
	s.h.RegisterAPI("publish",s.Publish)
}	
