// Code generated by go generate; DO NOT EDIT.
// This file was generated by gen.go at
// 2018-05-10 19:32:17.270949665 +0530 IST m=+0.020814436
package agent

// RegisterAllAPI ...
func (s *Service) RegisterAllAPI() {
	s.h.RegisterWildCardAPI(s.PassThru)
	s.h.RegisterAPI("getstreamitem", s.Getstreamitem)
	s.h.RegisterAPI("liststreamkeyitems", s.Liststreamkeyitems)
	s.h.RegisterAPI("publish", s.Publish)
}	
