// Code generated by go generate; DO NOT EDIT.
// This file was generated by gen.go at
// 2018-05-10 19:10:29.178862191 +0530 IST m=+0.001729796
package agent

// RegisterAllAPI ...
func (s *Service) RegisterAllAPI() {
	s.h.RegisterWildCardAPI(s.PassThru)
	s.h.RegisterAPI("getstreamitem", s.Getstreamitem)
	s.h.RegisterAPI("liststreamkeyitems", s.Liststreamkeyitems)
	s.h.RegisterAPI("publish", s.Publish)
}	
