//
// Code generated by go generate; DO NOT EDIT.
// This file was generated by gen.go
//

package mcservice

func (s *MCService) registerAllAPI() {
	s.registerWildCardAPI(s.passThru)
	s.registerAPI("getstreamitem", s.getstreamitem)
	s.registerAPI("liststreamkeyitems", s.liststreamkeyitems)
	s.registerAPI("publish", s.publish)
}	
