
// Code generated by go generate; DO NOT EDIT.
// This file was generated by gen.go

package mcservice

// RegisterAllAPI ...
func (s *Service) RegisterAllAPI() {
	s.h.RegisterWildCardAPI(s.PassThru)
	s.h.RegisterAPI("getstreamitem", s.Getstreamitem)
	s.h.RegisterAPI("liststreamkeyitems", s.Liststreamkeyitems)
	s.h.RegisterAPI("publish", s.Publish)
}	
